// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/model/book_source.dart';
import 'api/parse_book_source.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ReqwestErrorPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerreqwestError;

  @protected
  ReqwestError
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerreqwestError(
          dynamic raw);

  @protected
  ReqwestError
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerreqwestError(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BookSource dco_decode_book_source(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  RuleBookInfo dco_decode_box_autoadd_rule_book_info(dynamic raw);

  @protected
  RuleContent dco_decode_box_autoadd_rule_content(dynamic raw);

  @protected
  RuleExplore dco_decode_box_autoadd_rule_explore(dynamic raw);

  @protected
  RuleReview dco_decode_box_autoadd_rule_review(dynamic raw);

  @protected
  RuleSearch dco_decode_box_autoadd_rule_search(dynamic raw);

  @protected
  RuleToc dco_decode_box_autoadd_rule_toc(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<BookSource> dco_decode_list_book_source(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  RuleBookInfo? dco_decode_opt_box_autoadd_rule_book_info(dynamic raw);

  @protected
  RuleContent? dco_decode_opt_box_autoadd_rule_content(dynamic raw);

  @protected
  RuleExplore? dco_decode_opt_box_autoadd_rule_explore(dynamic raw);

  @protected
  RuleReview? dco_decode_opt_box_autoadd_rule_review(dynamic raw);

  @protected
  RuleSearch? dco_decode_opt_box_autoadd_rule_search(dynamic raw);

  @protected
  RuleToc? dco_decode_opt_box_autoadd_rule_toc(dynamic raw);

  @protected
  RuleBookInfo dco_decode_rule_book_info(dynamic raw);

  @protected
  RuleContent dco_decode_rule_content(dynamic raw);

  @protected
  RuleExplore dco_decode_rule_explore(dynamic raw);

  @protected
  RuleReview dco_decode_rule_review(dynamic raw);

  @protected
  RuleSearch dco_decode_rule_search(dynamic raw);

  @protected
  RuleToc dco_decode_rule_toc(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ReqwestError
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerreqwestError(
          SseDeserializer deserializer);

  @protected
  ReqwestError
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerreqwestError(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BookSource sse_decode_book_source(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RuleBookInfo sse_decode_box_autoadd_rule_book_info(
      SseDeserializer deserializer);

  @protected
  RuleContent sse_decode_box_autoadd_rule_content(SseDeserializer deserializer);

  @protected
  RuleExplore sse_decode_box_autoadd_rule_explore(SseDeserializer deserializer);

  @protected
  RuleReview sse_decode_box_autoadd_rule_review(SseDeserializer deserializer);

  @protected
  RuleSearch sse_decode_box_autoadd_rule_search(SseDeserializer deserializer);

  @protected
  RuleToc sse_decode_box_autoadd_rule_toc(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<BookSource> sse_decode_list_book_source(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RuleBookInfo? sse_decode_opt_box_autoadd_rule_book_info(
      SseDeserializer deserializer);

  @protected
  RuleContent? sse_decode_opt_box_autoadd_rule_content(
      SseDeserializer deserializer);

  @protected
  RuleExplore? sse_decode_opt_box_autoadd_rule_explore(
      SseDeserializer deserializer);

  @protected
  RuleReview? sse_decode_opt_box_autoadd_rule_review(
      SseDeserializer deserializer);

  @protected
  RuleSearch? sse_decode_opt_box_autoadd_rule_search(
      SseDeserializer deserializer);

  @protected
  RuleToc? sse_decode_opt_box_autoadd_rule_toc(SseDeserializer deserializer);

  @protected
  RuleBookInfo sse_decode_rule_book_info(SseDeserializer deserializer);

  @protected
  RuleContent sse_decode_rule_content(SseDeserializer deserializer);

  @protected
  RuleExplore sse_decode_rule_explore(SseDeserializer deserializer);

  @protected
  RuleReview sse_decode_rule_review(SseDeserializer deserializer);

  @protected
  RuleSearch sse_decode_rule_search(SseDeserializer deserializer);

  @protected
  RuleToc sse_decode_rule_toc(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerreqwestError(
          ReqwestError self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerreqwestError(
          ReqwestError self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_book_source(BookSource self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rule_book_info(
      RuleBookInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rule_content(
      RuleContent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rule_explore(
      RuleExplore self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rule_review(
      RuleReview self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rule_search(
      RuleSearch self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rule_toc(RuleToc self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_book_source(
      List<BookSource> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rule_book_info(
      RuleBookInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rule_content(
      RuleContent? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rule_explore(
      RuleExplore? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rule_review(
      RuleReview? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rule_search(
      RuleSearch? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rule_toc(
      RuleToc? self, SseSerializer serializer);

  @protected
  void sse_encode_rule_book_info(RuleBookInfo self, SseSerializer serializer);

  @protected
  void sse_encode_rule_content(RuleContent self, SseSerializer serializer);

  @protected
  void sse_encode_rule_explore(RuleExplore self, SseSerializer serializer);

  @protected
  void sse_encode_rule_review(RuleReview self, SseSerializer serializer);

  @protected
  void sse_encode_rule_search(RuleSearch self, SseSerializer serializer);

  @protected
  void sse_encode_rule_toc(RuleToc self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerreqwestError(
          dynamic ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerreqwestError(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerreqwestError(
          dynamic ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerreqwestError(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
class RustLibWasmModule implements WasmModule {
  @override
  external Object /* Promise */ call([String? moduleName]);

  @override
  external RustLibWasmModule bind(dynamic thisArg, String moduleName);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerreqwestError(
          dynamic ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerreqwestError(
          dynamic ptr);
}
